<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>58dc504e-9d75-4087-9bd9-33acc6324e1a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.*" />
    <PackageReference Include="Azure.AI.OpenAI" Version="2.*" />
    <PackageReference Include="Azure.AI.FormRecognizer" Version="4.*" />
    <PackageReference Include="Azure.Identity" Version="1.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CareerApp.Core\CareerApp.Core.csproj" />
    <ProjectReference Include="..\CareerApp.Infrastructure\CareerApp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
